Arguments: 
  /usr/local/Cellar/node/9.7.1/bin/node /usr/local/Cellar/yarn/1.5.1/libexec/bin/yarn.js update

PATH: 
  /Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/mysql/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Library/Frameworks/Python.framework/Versions/3.5/bin:/usr/local/mysql/bin:/usr/local/mongodb/bin:/usr/local/mongodb/bin

Yarn version: 
  1.5.1

Node version: 
  9.7.1

Platform: 
  darwin x64

npm manifest: 
  No manifest

yarn manifest: 
  No manifest

Lockfile: 
  No lockfile

Trace: 
  Error: Couldn't find a package.json file in "/Users/seppesnoeck/Documents/projects/twitter-clone"
      at new MessageError (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:186:110)
      at /usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:40048:15
      at Generator.next (<anonymous>)
      at step (/usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:98:30)
      at /usr/local/Cellar/yarn/1.5.1/libexec/lib/cli.js:109:13
      at <anonymous>
